### ISSUE TITLE
Feature Request : Publish to a topic !

### ISSUE THREAD

**Issue by quadcodes** [misterdanb/Espanol#1]
Excellent wrapper library for the esp8266 ! 
I have a feature request though. 
If you can implement all : subscribe, unsubscribe & publish. Then this library will complete.

**Comment by l-sch** [comment]
Thanks quadcodes.
Should be implemented in the next days, but I can't promise.

**Comment by l-sch** [comment]
Publish-Methods are now available. Thanks for your feedback!

**Comment by quadcodes** [comment]
Thanks for quick update !

But I'm facing issues.

Whenever I try unsubscribe [denada.unsubscribe("sometopic/#");], I get following error on my device serial after my device restarts to connect.
<code>
Exception (28):
epc1=0x4000bdc8 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3f
</code>

& While publishing [denada.publish("sometopic", "somemessage");]; My device connects to the broker but it publishes nothing. Here is the response from my broker while publishing.

<code>
newPacket { topic: 'echo/$SYS/41XHE-v3/new/clients',
payload: 'esp8266-a12',
retain: undefined,
qos: undefined }
</code>

I'm using "Mosca" on node server as broker. 
I have tested subscribe/unsubscribe/publish with generic ESP8266 library & it works fine with same server.

Is that I'm missing something OR using your library incorrectly ?

**Comment by l-sch** [comment]
So for me, the following code ...
```c++
#include <SPI.h>
#include <ESP8266WiFi.h>
#include <Espanol.h>

// WiFi-Credentials
char* broker   = "10.0.0.11";
int port       = 1883;

Espanol denada(ssid, password, broker, port, callback);

void callback(char* topic, byte* payload, unsigned int length)
{
    String msg = topic;
    msg += " - ";
    msg += (char*) payload;

    if (payload[0] == 'u') {
      denada.unsubscribe("foo/bar/#");
      Serial.println("Unsubscribed!");

      delay(1000);
      denada.subscribe("foo/bar/#");
      Serial.println("Subscribed again!");
    }

    Serial.println(msg);
}

void setup()
{
    Serial.begin(115200);

    denada.setDebug(true);
    denada.subscribe("foo/bar/#");
}

void loop()
{
    denada.loop();
}
```
... outputs this on my serial console, ...
```
.....
WiFi connected
IP address: 
10.0.0.111
Connecting to broker
Connected to MQTT broker
foo/bar/lol - Hello8266-360
Unsubscribed!
Subscribed again!
foo/bar/lol - unsubscribe60
foo/bar/lol - Worldscribe60
```
... which implies to me that, at least with our code, everything is fine.
Maybe I didn't understand your question correctly, did I?
